server:
    port: 8080
spring:
    application:
        name: apartment
    datasource:
        url: jdbc:postgresql://localhost:5432/db_apartment
        username: mithunkumarselvaraj
        password: Moni@202211
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: false
